repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: "v1.77.0"
  hooks:
    - id: terraform_fmt
      args:
        - "--args=-diff"
        - "--args=-check"
        - "--args=-recursive"
        - "--args=-list"
    - id: terraform_docs
      args:
        - "--hook-config=--path-to-file=./README.md"
        - "--hook-config=--add-to-existing-file=true"
        - "--hook-config=--lockfile=false"
    - id: infracost_breakdown
      args:
        - --args="--path=."
        - --hook-config='.totalHourlyCost|tonumber > 0.1'
        - --hook-config='.totalHourlyCost|tonumber > 1'
        - --hook-config='.projects[].diff.totalMonthlyCost|tonumber != 10000'
        - --hook-config='.currency == "USD"'
    - id: terraform_checkov
      args:
        - --args=--quiet
        - --args=--skip-check CKV2_AWS_8
    - id: terraform_validate
      args:
        - --args=-json
        - --args=-no-color
